version: '3'
services:

  consul:
    image: consul
    
  apigateway:
    build: ./api-gateway
    ports:
    - "8080:8080"
    depends_on:
      - "consul"
    
      
  ricette:
     build: ./ricette
     depends_on:
       - "consul"
     depends_on:
       - "postgres"
     depends_on:
       - "kafka"
     links:
      - kafka:kafka
     deploy:
        mode: replicated
        replicas: 2
     
      
  connessioni:
     build: ./connessioni
     depends_on:
      - "consul"
     depends_on:
       - "postgres2"
     depends_on:
       - "kafka"
     links:
      - kafka:kafka
     deploy:
        mode: replicated
        replicas: 2
        
  ricette-seguite:
    build: ./ricette-seguite
    depends_on:
      - "consul"
    depends_on:
       - "postgres3"
    depends_on:
       - "kafka"
    links:
      - kafka:kafka
    deploy:
        mode: replicated
        replicas: 2
    
      
  postgres:
    container_name: postgresServer1
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ricette
      
  postgres2:
    container_name: postgresServer2
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: connessioni
   
  postgres3:
    container_name: postgresServer3
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ricette-seguite
      
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - "zookeeper"
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "ricette-service-event-channel:2:1, connessioni-service-event-channel:2:1"
      

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
